twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - bootstrap_4_layout.html.twig
        # - autre-theme.html.twig
        # - dernier-theme.html.twig
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"